app/src/main/java/com/rozenkow/model/Person.java
package com.rozenkow.model;

import org.springframework.data.mongodb.core.index.TextIndexed;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by Poul Rozenkow.
 */
public class Person extends AuditEntity {
  @TextIndexed
  private String firstName;
  @TextIndexed
  private String lastName;
  @TextIndexed
  private String middleName;
  private String passportNumber;
  private String passportSeries;
  private Date birthDate;
  private Sex sex;
  private Address address1;
  private List<String> phones;

  public Person() {
    phones = new ArrayList<>();
    address1 = new Address();
  }

  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public String getPassportNumber() {
    return passportNumber;
  }

  public void setPassportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
  }

  public String getPassportSeries() {
    return passportSeries;
  }

  public void setPassportSeries(String passportSeries) {
    this.passportSeries = passportSeries;
  }

  public Date getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(Date birthDate) {
    this.birthDate = birthDate;
  }

  public Sex getSex() {
    return sex;
  }

  public void setSex(Sex sex) {
    this.sex = sex;
  }

  public Address getAddress1() {
    return address1;
  }

  public void setAddress1(Address address1) {
    this.address1 = address1;
  }

  public List<String> getPhones() {
    return phones;
  }

  public void setPhones(List<String> phones) {
    this.phones = phones;
  }

  public String getFullName() {
    return firstName + " " + lastName;
  }

  @Override
  public String toString() {
    return "Person{" +
           "firstName='" + firstName + '\'' +
           ", lastName='" + lastName + '\'' +
           ", middleName='" + middleName + '\'' +
           ", passportNumber='" + passportNumber + '\'' +
           ", passportSeries='" + passportSeries + '\'' +
           ", birthDate=" + birthDate +
           ", sex=" + sex +
           ", address1=" + address1 +
           ", phones=" + phones +
           '}';
  }
}

app/src/main/java/com/rozenkow/model/ui/CurrentVisit.java
package com.rozenkow.model.ui;

import com.rozenkow.model.MedicalRecord;
import com.rozenkow.model.Visit;

import java.io.Serializable;

/**
 * Created by Poul Rozenkow.
 */
public class CurrentVisit implements Serializable {
  private Visit visit;
  private MedicalRecord medicalRecord;

  public CurrentVisit(Visit visit, MedicalRecord medicalRecord) {
    this.visit = visit;
    this.medicalRecord = medicalRecord;
  }

  public Visit getVisit() {
    return visit;
  }

  public MedicalRecord getMedicalRecord() {
    return medicalRecord;
  }
}

app/src/main/resources/templates/schedule/current_visits.ftl
<#import "../fragments/page.master.ftl" as layout/>
<#include "../fragments/page.master.ftl"/>

<#assign layoutOut>
<script type="application/javascript">
    $("#home").addClass('active');
</script>

<form id="CurrentVisits" class="form-horizontal" method="get" action="/" modelAttribute="Visits">

    <@spring.bind "CurrentVisits"/>
    <@spring.bind "VisitStatuses"/>

    <div class="page-header">
        <h2>${springMacroRequestContext.getMessage('page.header.currentVisits')}</h2>
    </div>

  <#-- Visits -->
            <div class="panel panel-default">

                <div class="panel-body" id="visits">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th><@spring.message "page.field.visit.from"/></th>
                            <th><@spring.message "page.field.visit.to"/></th>
                            <th><@spring.message "page.field.visit.goal"/></th>
                            <th><@spring.message "page.field.visit.patient"/></th>
                            <th><@spring.message "page.field.visit.status"/></th>
                        </tr>
                        </thead>
                        <tbody>
                            <#list CurrentVisits>
                                <#items as scheduled_visit>
                                <tr>
                                    <td>${scheduled_visit.visit.from.format('HH:mm')}</td>
                                    <td>${scheduled_visit.visit.to.format('HH:mm')}</td>
                                    <td>${scheduled_visit.visit.goal}</td>
                                    <td>
                                        <a href="/medrecord/load/${scheduled_visit.medicalRecord.id}/edit">
                                            ${scheduled_visit.medicalRecord.patient.fullName}
                                        </a>
                                    </td>
                                    <td>${VisitStatuses[scheduled_visit.visit.status]}</td>
                                </tr>
                                </#items>
                            </#list>
                        </tbody>
                    </table>
                </div>
            </div> <!-- end of Visit -->

</form>

</#assign>

<@layout.indexmaster  nestedOut="${layoutOut}" titleKey="page.title.home"/>